# config.py — Country → Currency mapping + currency symbol map

COUNTRY_TO_CURRENCY: dict[str, str] = {
    # Asia
    "india": "INR",
    "china": "CNY",
    "japan": "JPY",
    "south korea": "KRW",
    "korea": "KRW",
    "singapore": "SGD",
    "thailand": "THB",
    "indonesia": "IDR",
    "malaysia": "MYR",
    "philippines": "PHP",
    "vietnam": "VND",
    "bangladesh": "BDT",
    "pakistan": "PKR",
    "sri lanka": "LKR",
    "nepal": "NPR",
    "myanmar": "MMK",
    "cambodia": "KHR",
    "taiwan": "TWD",
    "hong kong": "HKD",
    "macau": "MOP",

    # Middle East
    "uae": "AED",
    "united arab emirates": "AED",
    "saudi arabia": "SAR",
    "qatar": "QAR",
    "kuwait": "KWD",
    "bahrain": "BHD",
    "oman": "OMR",
    "jordan": "JOD",
    "israel": "ILS",
    "turkey": "TRY",
    "iran": "IRR",
    "iraq": "IQD",
    "lebanon": "LBP",

    # Europe
    "germany": "EUR",
    "france": "EUR",
    "italy": "EUR",
    "spain": "EUR",
    "portugal": "EUR",
    "netherlands": "EUR",
    "belgium": "EUR",
    "austria": "EUR",
    "greece": "EUR",
    "finland": "EUR",
    "ireland": "EUR",
    "luxembourg": "EUR",
    "slovakia": "EUR",
    "slovenia": "EUR",
    "estonia": "EUR",
    "latvia": "EUR",
    "lithuania": "EUR",
    "malta": "EUR",
    "cyprus": "EUR",
    "united kingdom": "GBP",
    "uk": "GBP",
    "great britain": "GBP",
    "switzerland": "CHF",
    "sweden": "SEK",
    "norway": "NOK",
    "denmark": "DKK",
    "poland": "PLN",
    "czech republic": "CZK",
    "czechia": "CZK",
    "hungary": "HUF",
    "romania": "RON",
    "bulgaria": "BGN",
    "croatia": "EUR",
    "serbia": "RSD",
    "ukraine": "UAH",
    "russia": "RUB",

    # Americas
    "united states": "USD",
    "usa": "USD",
    "us": "USD",
    "america": "USD",
    "canada": "CAD",
    "mexico": "MXN",
    "brazil": "BRL",
    "argentina": "ARS",
    "colombia": "COP",
    "chile": "CLP",
    "peru": "PEN",
    "venezuela": "VES",
    "ecuador": "USD",
    "bolivia": "BOB",
    "uruguay": "UYU",
    "paraguay": "PYG",

    # Africa
    "south africa": "ZAR",
    "nigeria": "NGN",
    "kenya": "KES",
    "ghana": "GHS",
    "ethiopia": "ETB",
    "egypt": "EGP",
    "morocco": "MAD",
    "tanzania": "TZS",
    "uganda": "UGX",
    "algeria": "DZD",
    "tunisia": "TND",

    # Oceania
    "australia": "AUD",
    "new zealand": "NZD",
    "fiji": "FJD",
    "papua new guinea": "PGK",
}

# Currency symbol → possible ISO codes (used for OCR sanity check)
SYMBOL_TO_CURRENCIES: dict[str, list[str]] = {
    "$": ["USD", "CAD", "AUD", "SGD", "HKD", "NZD", "MXN"],
    "€": ["EUR"],
    "£": ["GBP"],
    "₹": ["INR"],
    "¥": ["JPY", "CNY"],
    "₩": ["KRW"],
    "₺": ["TRY"],
    "₽": ["RUB"],
    "฿": ["THB"],
    "₫": ["VND"],
    "₱": ["PHP"],
    "﷼": ["SAR", "QAR", "IRR", "OMR", "YER"],
    "د.إ": ["AED"],
    "kr": ["SEK", "NOK", "DKK"],
    "zł": ["PLN"],
    "₴": ["UAH"],
    "₦": ["NGN"],
    "₵": ["GHS"],
    "R": ["ZAR"],
    "rm": ["MYR"],
    "rp": ["IDR"],
}

# ISO currency codes recognised in OCR text
KNOWN_CURRENCY_CODES: set[str] = {
    "USD", "EUR", "GBP", "INR", "JPY", "CNY", "AED", "SAR", "QAR",
    "KWD", "BHD", "OMR", "SGD", "HKD", "TWD", "KRW", "THB", "MYR",
    "IDR", "PHP", "VND", "PKR", "BDT", "LKR", "NPR", "AUD", "NZD",
    "CAD", "MXN", "BRL", "ARS", "COP", "CLP", "ZAR", "NGN", "KES",
    "GHS", "EGP", "MAD", "TRY", "RUB", "PLN", "SEK", "NOK", "DKK",
    "CHF", "CZK", "HUF", "RON", "BGN", "UAH", "ILS", "JOD",
}
